name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run benchmark
        run: |
          go test -bench=. -benchmem ./... > result.txt

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: result.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: 'benchmark-data'
          auto-push: true