name: Build and Publish CLI

on:
  release:
    types: [published]
  push:
    branches:
      - main
      - feat/sign-apple-os-cli

concurrency:
  group: publish-cli-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'arm64_runner' || 'ubuntu-latest' }}
    if: github.repository == 'langgenius/dify-plugin-daemon'
    strategy:
      matrix:
        include:
          - platform: linux/amd64
          - platform: linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Transform platform
        run: |
          GOARCH=$(echo "${{ matrix.platform }}" | cut -d '/' -f 2)
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Build CLI
        run: |
          go mod tidy
          CGO_ENABLED=0 GOOS=windows GOARCH=${{ env.GOARCH }} go build -ldflags "-X 'main.VersionX=v${{ github.event.release.tag_name }}'" -o dify-plugin-windows-${{ env.GOARCH }}.exe ./cmd/commandline
          CGO_ENABLED=0 GOOS=darwin GOARCH=${{ env.GOARCH }} go build -ldflags "-X 'main.VersionX=v${{ github.event.release.tag_name }}'" -o dify-plugin-darwin-${{ env.GOARCH }} ./cmd/commandline
          CGO_ENABLED=0 GOOS=linux GOARCH=${{ env.GOARCH }} go build -ldflags "-X 'main.VersionX=v${{ github.event.release.tag_name }}'" -o dify-plugin-linux-${{ env.GOARCH }} ./cmd/commandline

      - name: Publish CLI
        run: |
          gh release upload ${{ github.event.release.tag_name }} dify-plugin-windows-${{ env.GOARCH }}.exe --clobber
          gh release upload ${{ github.event.release.tag_name }} dify-plugin-darwin-${{ env.GOARCH }} --clobber
          gh release upload ${{ github.event.release.tag_name }} dify-plugin-linux-${{ env.GOARCH }} --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sign-macos-binary:
    needs: build
    runs-on: macos-latest
    if: github.repository == 'langgenius/dify-plugin-daemon'
    strategy:
      matrix:
        include:
          - platform: arm64
          - platform: amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up certificate
        run: |
          echo "${{ secrets.MACOS_CERTIFICATE }}" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "${{ secrets.MACOS_CERT_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: dify-plugin-darwin-${{ matrix.platform }}
          repository: langgenius/dify-plugin-daemon
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: dify-plugin-darwin-${{ matrix.platform }}
          repository: langgenius/dify-plugin-daemon
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign binary
        run: |
          codesign --timestamp --options=runtime --sign "${{ secrets.MACOS_CERT_NAME }}" ./dify-plugin-darwin-${{ matrix.platform }}

      - name: Create zip for notarization
        run: |
          zip -r dify-plugin-darwin-${{ matrix.platform }}.zip ./dify-plugin-darwin-${{ matrix.platform }}

      - name: Notarize binary
        run: |
          xcrun notarytool submit dify-plugin-darwin-${{ matrix.platform }}.zip \
            --apple-id "${{ secrets.AC_USERNAME }}" \
            --password "${{ secrets.AC_PASSWORD }}" \
            --team-id "${{ secrets.TEAM_ID }}" \
            --wait

      - name: Staple notarization ticket to binary
        run: |
          xcrun stapler staple ./dify-plugin-darwin-${{ matrix.platform }}

      - name: Verify signature
        run: |
          spctl --assess --type exec --verbose=4 ./dify-plugin-darwin-${{ matrix.platform }}

      - name: Upload signed binary
        uses: actions/upload-artifact@v3
        with:
          name: dify-plugin-darwin-${{ matrix.platform }}
          repository: langgenius/dify-plugin-daemon
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload signed binary
        run: |
          # remove already uploaded binaries
          gh release delete ${{ github.event.release.tag_name }} --yes
          # upload signed binaries
          gh release upload ${{ github.event.release.tag_name }} dify-plugin-darwin-${{ matrix.platform }} --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
